version: '3'

networks:
  parser-network:
    driver: bridge

services:

        parser:
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - parser-network
            volumes:
                - ./../parser:/parser:rw,cached
                - parser_log:/parser/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - mariadb

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "81:80"
                - "443:443"
            networks:
                - parser-network
            depends_on:
                - parser
            volumes:
                - ./../parser/public:/parser/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            ports:
                - "6379:6379"
            networks:
                - parser-network

        memcached:
            container_name: memcached
            image: memcached:latest
            ports:
                    - "11211:11211"
            networks:
                - parser-network

        mariadb:
            container_name: mariadb
            image: mariadb:latest
            env_file:
                - ./db/master/.env.master
            ports:
                - "3307:3306"
            volumes:
                - ./db/master/.data/mysql:/var/lib/mysql:rw
            networks:
                - parser-network

volumes:
    nginx_log:
    parser_log:
    db:
        driver: local

